### ISSUE TITLE
简直是智障

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinideastudio/GameUI#1]
居然有人能傻逼到把.VC.db加到git里面@DREAMWORLDVOID

**Comment by DLaboratory** [comment]
莫名中枪，为啥叫上我。

**Comment by ascchrvalstr** [comment]
@DLaboratory 让你出来说：这个项目迟早要完

**Comment by ascchrvalstr** [comment]
@DLaboratory 让你出来说：这个项目迟早要完

**Comment by DLaboratory** [comment]
请问这位记者，我在什么场合说过“把平台相关的二进制缓存数据库文件加入到Git库会导致项目的完蛋”？这些无中生有的事情，你再说一遍，等于说，你也有责任吧。

**Comment by DREAMWORLDVOID** [comment]
@ascchrvalstr 看不惯就别说话。这个我自己都没发现，电脑又抽风了，过两天有空了我洗掉就是了
