### ISSUE TITLE
将c++接口改为c接口

### ISSUE THREAD

**Issue by abc612008** [Infinideastudio/GameUI#4]
否则会调用不正常
（各种模式/编译器里标准库/STL的实现都不同）

**Comment by DREAMWORLDVOID** [comment]
明白了，可能的话提供C接口

**Comment by DLaboratory** [comment]
提醒一下:注意ABI问题

**Comment by abc612008** [comment]
@DLaboratory 其实我说的就是ABI问题，目前解决方案是要用到UIlib的软件都自己编译一个UILIB
（@DREAMWORLDVOID 的方案是钦点某一个编译器的某一个版本的某一个设置）

**Comment by DLaboratory** [comment]
好吧，这也算是一个解决方法。
