### ISSUE TITLE
用SDL_TTF代替freetype

### ISSUE THREAD

**Issue by abc612008** [Infinideastudio/GameUI#9]
> 话说你们放着sdlttf不用跑去用什么freetype啊
> freetype有坑，linux上最新neworld段错误
——@Miigon

**Comment by Miigon** [comment]
这个锅指向明确，立意深刻，言简意赅

**Comment by DREAMWORLDVOID** [comment]
@abc612008 Linux上freetype的安装有点奇怪，包含目录需要特殊配置，这个锅我不接

**Comment by Miigon** [comment]
奇怪到apt安装的版本一个FT_New_Face在win上能跑linux上段错误

**Comment by Miigon** [comment]
算了，在这里喊也没人听，等LGEMU告一段落我自己改改好了
NEWorld的进度这几天几乎都0了

**Comment by DREAMWORLDVOID** [comment]
段错误是因为字体文件没放吧 @Miigon

**Comment by DREAMWORLDVOID** [comment]
而且SDL_TTF的内核也是freetype

**Comment by Miigon** [comment]
字体文件放哪？
只能用固定的字体文件么？
没法设置？
也不加个文件检测啥的。。。

**Comment by DREAMWORLDVOID** [comment]
放哪里是自己通过搜索路径定义的，但搜索还没完成

**Comment by Miigon** [comment]
Close吧
